from bson import ObjectId
from helpers.helper import currTime
from database.database import client

from services.transaction_services import createTxnDB

db = client["simple_bank_db"]

accCol = db["Accounts"]

def getAccountsDB():
    res = list(accCol.find())
    for r in res:
        r["_id"] = str(r["_id"])
        r["userId"] = str(r["userId"])

    return res
    
def getAccountDB(accountId: str):
    if not ObjectId.is_valid(accountId):
        return False
    res = accCol.find_one({"_id": ObjectId(accountId)})
    if res:
        res["_id"] = str(res["_id"])
        res["userId"] = str(res["userId"])

    return res

def getAccountTxnDB(accountId: str):
    if not ObjectId.is_valid(accountId):
        return False
    res = next(accCol.aggregate([ 
        { 
            "$match": { "_id": ObjectId(accountId) }, 
        }, 
        { 
            "$lookup": { 
                "from": "Transactions", 
                "localField": "_id", 
                "foreignField": "accountId", 
                "as": "transactions" 
            } 
        }, 
    ]), None)

    if res:
        res["_id"] = str(res["_id"])
        res["userId"] = str(res["userId"])
        for a in res["transactions"]:
            a["_id"] = str(a["_id"])
            a["accountId"] = str(a["accountId"])

    print(res)

    return res

def accountTxnDB(accountId: str, txnType: str, amount: float, description: str, transferId: str = ''):
    """
        Function to deal with all kinds of transaction types from a single account.

        txnType is hard-coded to be either deposit, withdraw, or transfer.
        transfer_id only comes into play if txnType is transfer, else do not need to be passed in.

        Function will either return:
            On success: an object that contains success messages generated by Mongo DB Cloud Atlas.
            On fail: an error code number depending on the issue. Router will handle each error code's output.
    """
    if not ObjectId.is_valid(accountId) or (txnType == "transfer" and not ObjectId.is_valid(transferId)):
        return False
    
    if txnType == "deposit":
        # First gets the account to do some basic authentication checks
        account = getAccountDB(accountId)
        # If account does not exist, returns 404 (Not Found)
        if not account:
            return 404
        # If the account is closed, should not be able to do any transaction with the account. Returns 403 (Forbidden)
        if account["status"] == "closed":
            return 403
        # First creates a transaction history 
        createTxnDB(accountId, txnType, amount, account["balance"]+amount, description)
        # Returns a success object that will be displayed by the router
        return accCol.update_one(
            {"_id": ObjectId(accountId)},
            { "$inc": {"balance": amount}}
        )
    elif txnType == "withdraw":
        account = getAccountDB(accountId)
        if not account:
            return 404
        if account["status"] == "closed":
            return 403
        if account["balance"] < amount:
            return 422
        createTxnDB(accountId, txnType, amount, account["balance"]-amount, description)
        return accCol.update_one(
            {"_id": ObjectId(accountId)},
            { "$inc": {"balance": -amount}}
        )
    elif txnType == "transfer":
        accFrom = getAccountDB(accountId)
        if not accFrom:
            return 404
        if accFrom["status"] == "closed":
            return 403
        if accFrom["balance"] < amount:
            return 422
        accTo = getAccountDB(transferId)
        if not accTo:
            return 404
        if accTo["status"] == "closed":
            return 403

        createTxnDB(accountId, txnType, amount, accFrom["balance"]-amount, description)
        txnFrom = accCol.update_one(
            {"_id": ObjectId(accountId)},
            { "$inc": {"balance": -amount}}
        )

        createTxnDB(transferId, txnType, amount, accTo["balance"]+amount, description)
        txnTo = accCol.update_one(
            {"_id": ObjectId(transferId)},
            { "$inc": {"balance": amount}}
        )

        return {"from": txnFrom,
                "to": txnTo}


def createAccountDB(userId: str, balance: float, accountType: str, status: str):
    return accCol.insert_one({
            "userId": ObjectId(userId),
            "balance": balance,
            "accountType": accountType,
            "status": status,
            "createdAt": currTime()
        })

def updateAccountDB(accountId: str, balance: int, accountType: str, status: str):
    if not ObjectId.is_valid(accountId):
        return False
    return accCol.update_one(
        {"_id": ObjectId(accountId)},
        { "$set": {"balance": balance, "accountType": accountType, "status": status}}
    )

def deleteAccountDB(accountId: str):
    if not ObjectId.is_valid(accountId):
        return False
    return accCol.update_one(
        {"_id": ObjectId(accountId)},
        { "$set": {"status": "closed", "closedAt": currTime()}}
    )

def deleteAccountsDB(userId: str):
    if not ObjectId.is_valid(userId):
        return False
    return accCol.update_many(
        {"userId": ObjectId(userId)},
        {"$set": {"status": "closed", "closedAt": currTime()}}
    )